name: Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.php'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.php'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install system packages
        run: sudo apt-get update --allow-releaseinfo-change && sudo apt-get install -y curl zip

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite3, pdo_sqlite
          tools: composer:v2, php-cs-fixer
          coverage: none
        env:
          fail-fast: true

      - name: Environment
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        working-directory: app

      - name: Validate composer
        run: composer validate
        working-directory: app

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: app

      - name: Generate encryption key
        run: php artisan key:generate
        working-directory: app

      - name: Code Style (Laravel Pint)
        run: vendor/bin/pint --test
        working-directory: app

      - name: Pest in parallel
        run: vendor/bin/pest --parallel --processes=4
        working-directory: app

      - name: PHPStan tests
        run: vendor/bin/phpstan --memory-limit=1G analyse
        working-directory: app
